### ISSUE TITLE
Missing arrow in tooltip.

### ISSUE THREAD

**Issue by c0brarules** [nico3333fr/jquery-accessible-simple-tooltip-aria#5]
Hi Nicolas.

I'm not sure if this is the place to say this but I wanted to say thanks very much for taking the time to create these awesome accessible plugins.

I am having some problems however with the '**jquery-accessible-simple-tooltip-aria**' plugin.

I copied and pasted your code as you included on the http://a11y.nicolas-hoffmann.net/simple-tooltip/ webpage but for some reason in **Firefox v47.0**, **Chrome v51.0** and **Internet Explorer 11.0** I see the black tooltip boxes but the arrow is not aligned properly and appears inside the tooltip, slightly covering the first letter appearing in the tooltop box.

It seems to appear fine in your samples on your actual http://a11y.nicolas-hoffmann.net/simple-tooltip/ webpage so perhaps another style on that page is making them look as intended.

I am including a link to Codepen where I pasted your examples for you to check out. The only modifications I made to the code was spacing and line breaks.

http://codepen.io/c0brarules/pen/BzpMqW

Could you please let me know what changes I need to make to have the arrow appear as it does on your actual sample page?

Thanks again.

Dwayne

**Comment by nico3333fr** [comment]
Hi @c0brarules,

thanks for your message. ;)

It took me some time to understand where the problem was, as you've done perfectly! :)

In fact, it is my mistake: it comes from a piece of code I have included in the CSS for the demo, but not in the documentation. It is the box sizing, try adding this in the demo: 

```
html { box-sizing: border-box; }
*, *:before, *:after {
  box-sizing: inherit;
}
```
And everything will be displayed fine. I will update the documentation to avoid this issue again.

Thanks,
Nicolas

**Comment by c0brarules** [comment]
Hi Nicolas.

Wow, thanks very much for the quick response. I appreciate that.

I'm glad I could help and yes, that did the trick.
:-)

I do have another question for you though if you don't mind.

Is there a way to make it so that the Tooltip will
automatically/intelligently detect the four edges of the browser window so
that the Tooltip will switch from right/left/bottom/top based on how close
it appears to the edge/viewport of a webpage? That way it is always
displaying itself in full view of the user. I would still want to specify a
default, but it would be overwritten based on distance to edge/viewport of
the browser window.

In other words, if I have a long sentence that goes all the way from the
left side of the browser window to the right side of a browser window it
would be nice if the Tooltip would move from it's default right side of the
sentence to either below or above it. Otherwise what happens is it gets
hidden and can't be scrolled to see the entire Tooltip.

I am including a screenshot for you as well as the CodePen example using
your default code examples.

http://codepen.io/c0brarules/pen/BzpMqW


​

I know you supplied in your example the media-queries for tablets/mobile
(thanks by the way) for the Tooltip to switch below the text rather than to
the right of it however I want this to occur regardless of the screen size.

I know that may be a lot to ask for and if you don't have time to show me
what would need to be changed, could you please at least show me what to
change in the CSS to make the tooltip always appear above the hovered text,
rather than to the right of it?

Thanks again for your time.

- c0brarules

**Comment by nico3333fr** [comment]
> Hi Nicolas.

Hi again !

> Wow, thanks very much for the quick response. I appreciate that.
> I'm glad I could help and yes, that did the trick.
> :-)

Cool :)
Sorry for the delay for this answer, very busy :-\

> I do have another question for you though if you don't mind.

> Is there a way to make it so that the Tooltip will automatically/intelligently detect the four edges of the browser window so that the Tooltip will switch from right/left/bottom/top based on how close
it appears to the edge/viewport of a webpage? That way it is always displaying itself in full view of the user. I would still want to specify a default, but it would be overwritten based on distance to edge/viewport of the browser window.
> In other words, if I have a long sentence that goes all the way from the left side of the browser window to the right side of a browser window it would be nice if the Tooltip would move from it's default right side of the sentence to either below or above it. Otherwise what happens is it gets
hidden and can't be scrolled to see the entire Tooltip.

I've already thought to this feature, but I never had the time to implement it. My tooltip is for rather "controlled" environment. I hope to add it in a not-too-far future :)


​> I know you supplied in your example the media-queries for tablets/mobile
(thanks by the way) for the Tooltip to switch below the text rather than to
the right of it however I want this to occur regardless of the screen size.
> I know that may be a lot to ask for and if you don't have time to show me
what would need to be changed, could you please at least show me what to
change in the CSS to make the tooltip always appear above the hovered text,
rather than to the right of it?

It is a pure CSS issue :) so I've made an example here : http://codepen.io/nico3333fr/pen/RRpvrd

> Thanks again for your time.

You're welcomed.

**Comment by c0brarules** [comment]
Hi Nicolas.

I can believe you are quite busy and that is why it means even more to me
that you were willing to take the time to help me out.

I work at the University of Guelph in Ontario Canada and I help build
courses for students taking courses online. I really appreciate the time
you have taken to help me, and for all the accessible plug-ins you have
created that will be such a big help for the students with disabilities
that will be able to benefit from them when I implement them into the
courses.

I used the CSS you modified for me and from that I was able to create an
additional style that allows me to specify that the Tool-tip appears below
the hovered text. So now I can select above or below the hovered text as
required which should get me by until you have the time to implement the
new feature of having them appear automatically as needed.
:-)

Thanks again and have a great day!

- Dwayne
